services:
  - type: web
    name: gamex-backend
    runtime: node
    repo: https://github.com/VivanDg/Comercio-Electronico-GAMEX
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && node prisma/seed.js && npm start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: API_PREFIX
        value: /api/v1
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        value: gamex-production-jwt-secret-2026-min-32-chars
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_COOKIE_NAME
        value: gamex_token
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: MERCADOPAGO_ACCESS_TOKEN
        value: APP_USR-3637788754419884-062413-39294f1beecb1dc47079b0b3a5b59077-3494430641
      - key: MERCADOPAGO_NOTIFICATION_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: Gamex Import <noreply@gameximport.com>
      - key: ADMIN_EMAIL
        value: admin@gameximport.com
      - key: ADMIN_PASSWORD
        value: Admin123!
